[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
puppet_master = "5qPWqmiH7XAEyg14rqCm1LgmqhdT7DYsbnM5g2hZ2mVZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/urani/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
