[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
puppet_master = "DrL7fRZQKqF7GQuvzxYe4K6MV4inzodj8dhr1PPV8Fqr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/m/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
